on: push
jobs: 
build-node:
   runs-on: ubuntu-lastest
    container: nodejs:14
    steps:
      - run: yarn
      - run: npm install dotenv
      - run: npm install @ffmpeg-installer/ffmpeg
      - run: npm install @ffmpeg/ffmpeg
      - run: npm install
      - run: node index.js
